mysite/Somos/urls.py
"""
Created by Framework
This file is where you can set the urls to your views.
Modified by: Jorge Nino
Date: 19/10/18
"""
# Import libraries needed
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Set the name of the app
app_name = 'Somos'

# Declare the url patterns of the app views
urlpatterns = [
    # ex: /polls/
    path('quiensomos/', views.quiensomos, name='quiensomos'),
]

mysite/catalogo/urls.py
"""
Created by Framework
This file is where you can set the urls to your views.
Modified by: Jorge Nino
Date: 19/10/18
"""

# Import libraries used
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Set the name of the app
app_name = 'Catalogo'
# Declare the url patterns for each view.
urlpatterns = [
    # ex: /polls/

    path('search-submit/', views.SearchSubmitView.as_view(), name='search-submit'),
    path('search-ajax-submit/', views.SearchAjaxSubmitView.as_view(), name='search-ajax-submit'),

    path('catalogo/',views.catalogo,name='catalogo'),
    path('AJAXSearchCat/', views.AJAXSearchCat, name='ajaxSearchCat'),

    path('catalogo2/', views.catalogoFilter.as_view(),name='catalogo2'),
    path('catalogo/<int:productoid>/', views.getProducto, name='producto'),
    path('carrito/', views.viewCart, name='carrito'),
    path('checkout/', views.checkout, name = 'checkout'),
]
# if debug is on show images through their url.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('Inicio.urls')),
    path('',include('Comunidades.urls')),
    path('',include('Catalogo.urls')),
    path('',include('Somos.urls')),
    path('',include('Contacto.urls')),
    path('',include('Actividades.urls')),
    path('',include('Colabora.urls')),
    path('admin/', admin.site.urls),

    path('', include('accounts.urls')),
    path('', include('shopping_cart.urls')),

]

mysite/shopping_cart/urls.py
# from django.conf.urls import url

from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views

# from .views import (
#     add_to_cart,
#     delete_from_cart,
#     order_details,
#     checkout,
#     update_transaction_records,
#     success
# )

app_name = 'shopping_cart'

urlpatterns = [
    url(r'^add-to-cart/(?P<productoid>[-\w]+)/$', views.add_to_cart, name="add_to_cart"),
    url(r'^order-summary/$', views.order_details, name="order_summary"),
    url(r'^success/$', views.success, name='purchase_success'),
    url(r'^item/delete/(?P<productoid>[-\w]+)/$', views.delete_from_cart, name='delete_item'),
    url(r'^checkout/$', views.checkout, name='checkout'),
    url(r'^update-transaction/(?P<token>[-\w]+)/$', views.update_transaction_records,
        name='update_records')
]

mysite/catalogo/views.py
"""
Created by Framework
This file is where you can create views for the App
Modified by: Enrique Posada
Date: 03/11/18
"""
# Import the libraries used.
from django.shortcuts import render
from django.views.generic import View
from django.template import loader
from django.views.generic import ListView, DetailView
from django.http import JsonResponse
from django.core.paginator import EmptyPage, PageNotAnInteger, Paginator
from django.http import HttpResponse, HttpResponseRedirect
from Catalogo.models import *
# from Catalogo.models import UserSession
from rest_framework.views import APIView
from rest_framework.response import Response
from Catalogo.filters import *
from django.contrib import messages
from Comunidades.models import *
from Contacto.models import Contacto
# from django.urls import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404

from Catalogo.forms import *


import json

import re



# This function searches for the data of a Product when submitted
class SearchSubmitView(View):
    template = 'search_submit.html'
    """
    template = 'search_results.html'
    """
    response_message = 'This is the response'

    def post(self, request):
        template = loader.get_template(self.template)
        query = request.POST.get('search', '')

        # A simple query for Item objects whose title contain 'query'
        items = Noticia.objects.filter(titulo__icontains=query)

        context = {'title': self.response_message, 'query': query, 'items': items}

        rendered_template = template.render(context, request)
        return HttpResponse(rendered_template, content_type='text/html')

class SearchAjaxSubmitView(SearchSubmitView):
    template = 'search_results.html'
    response_message = 'This is the AJAX response'



def AJAXSearchCat(request):
    if(request.POST.get('precio__gt')!= None and request.POST.get('precio__gt')!=''):
        pgt = int(request.POST.get('precio__gt'))
    else:
        pgt = 0

    if(request.POST.get('precio__lt')!= None and request.POST.get('precio__lt')!=''):
        plt = int(request.POST.get('precio__lt'))
    else:
        plt = 999999

    if(request.POST.get('nombre') != None):
        nombre = request.POST.get('nombre')
    else:
        nombre = ''

    if(request.POST.get('comunidad') != None):
        com = request.POST.get('comunidad')
    else:
        com = ''

    coms = Comunidad.objects.filter(nombre__icontains=com)
    result = Producto.objects.filter(nombre__icontains=nombre)
    result = result.filter(communidad__in=coms)
    result = result.filter(precio__gte=pgt)
    result = result.filter(precio__lte=plt)

    return render(request,"Catalogo/cat_results.html", {'result':result})
#    html = render_to_string("/Comunidades/com_results.html", {'result':result})
#    return HttpResponse(html)


# Declare the view for accesing the Catalogo site.
def catalogo(request):
    contacto_list = Contacto.objects.all()
    # Get all the objects of Product from the DB.
    product_list = Producto.objects.all()
    # Set a paginator of 9 objects.
    paginator = Paginator(product_list,9)
    communities = Comunidad.objects.all()
    # Get the site of the view.
    page = request.GET.get('page')
    # Set the paginator to the site.
    products = paginator.get_page(page)
    # Declare a dict with the data passed to the view.
    if len(contacto_list)>=3:
        contacto_list = contacto_list[:3]
    entry_dict = {"products":products, "communities": communities,"contacto":contacto_list}
    # Render the view.
    return render(request,'Catalogo/catalogo.html',context=entry_dict)


# This function filters the data of a Product.
class catalogoFilter(ListView):
    model = Producto
    template_name = 'Catalogo/catalogoFilter.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['filter'] = CatalogoFilter(self.request.GET, queryset=self.get_queryset())
        return context



def getProducto(request, productoid):
    # try:
    producto = get_object_or_404(Producto, pk=productoid)
    if request.method == 'POST':
        quantity = request.POST.get('quantity')
        cart = request.session.get('cart', {})
        total = int(quantity) * float(producto.precio)
        # total_cart = request.session.get('total', 0)
        print('Quantity('+ str(quantity) +') * Price('+ str(producto.precio) +') = ' + str(total))
        cart[producto.nombre] = total # quantity.... Quantity of one by the moment
        request.session['cart'] = cart


        # Dictionary made in order to store product with it's quantity
        quantity_dict = request.session.get('quantity_dict', {})
        quantity_dict[producto.nombre] = quantity
        request.session['quantity_dict'] = quantity_dict

        # print(cart[productoid])

        print('Item has been added to the cart')
        messages.success(request, 'El producto se ha agregado a tu carrito de compras. Puedes revisarlo seleccionando el icono de tu carrito de compras')
        # for key, value in cart.items():

        # total_cart += value

        # request.session['total'] = total_cart

        # total = float(request.session.get('total_cart', re('"', '')))
        # total = total + (float(producto.precio) * int(quantity))  # quantity.... Quantity of one by the moment
        # request.session['total_cart'] = total
        # print('Total in cart is currently of: ' + total)

        # for item in cart:
            # print (item)
        print('Item with total: $'+str(cart[producto.nombre]))
        print('Quantity: ' +str(quantity_dict[producto.nombre]))
            # for y in cart[item]: # y = quantity, should print 1
            #     print (y+':'+cart[item][y]) # Print the current cart
        # print('Item:'+cart[productoid]+' has been added to the Cart')
        # productname = get_object_or_404(Producto, nombre)
    # except:
    #     raise Http404("El producto no existe")
    # return HttpResponse("Este es el Producto %s." % productoid)
    return render(request, 'Catalogo/productoinfo.html', {'producto': producto})

# This functions basically calls all of the items stored in the session alongside the quantity of the product
def viewCart(request):
    cart = request.session.get('cart', {})
    quantity_dict = request.session.get('quantity_dict', {})
    request.session['total'] = sum(cart.values())

    # products_list = Producto.objects.all()
    # for item, price in cart.items():
    #     producto = get_object_or_404(Producto, nombre = item)
    images_list = []
    products_list = Producto.objects.all()
    for i in products_list:
        if len(i.imagenes.all())>0:
            images_list.append(i.imagenes.all()[0])

    entry_dict = {
        "cart":cart,
        "quantity_dict":quantity_dict,
        "products":products_list,
        "products_images":images_list
    }

    #just declare another dictionary inside the if

    # for item in cart:
    #     print (item)
    if request.method == 'POST':
        # boton = request.POST.get('boton'+item)
        for item, price in cart.items():
            # print(item)
            if request.POST.get('boton'+item):



                boton = request.POST.get('boton'+item)
                print(item+' button has been pressed')
                # item_to_remove = cart[item]
                # del item_to_remove
                # cart.pop(item)
                # del cart[item]

                # new_total = request.session.get('total')

                # new_total -= float(price)

                # print('New TOTAL: $' + str(new_total))

                # request.session['total'] = 0


                new_cart = removefromCart(cart, item)

                # cart = new_cart # Equivalent line is below
                request.session['cart'] = new_cart

                messages.success(request, 'El producto "'+str(item)+'" se ha removido de tu carrito de compras.')

                # Uses same function in order to remove from both dictionaries
                new_quantity_dict = removefromCart(quantity_dict, item)
                request.session['quantity_dict'] = new_quantity_dict

                prev_val = sum(cart.values())
                print('Previous Total: $' + str(prev_val))

                request.session['total'] = sum(new_cart.values())

                new_val = sum(new_cart.values())

                print('New total: $' + str(new_val))

                print('The product '+item+' has been removed from the Cart')

                new_entry_dict = {
                    "cart":new_cart,
                    "quantity_dict":quantity_dict,
                    "products":products_list,
                    "products_images":images_list
                }

                cart = new_cart
                return render(request, 'Catalogo/shoppingcart.html', context = new_entry_dict)
        # print('Button pressed was: '+boton)
        # if request.POST.get('checkout'):
            # print('Se presiono ir a checkout')
            # return render(request, 'Catalogo/checkout.html', {'cart':cart})
    # else:
    return render(request, 'Catalogo/shoppingcart.html', context = entry_dict)
    # return HttpResponse("Este es el carrito %s." % json.dumps(cart))
        # for y in cart[item]: # y = quantity, should print 1
            # print (y,':',cart[item][y]) # Print the current cart


    # {'cart':cart}
    # {'cart':new_cart}


# This function removes the item from the cart
def removefromCart(cart, key):
    new_cart = dict(cart)
    del new_cart[key]
    return new_cart



def checkout(request):
    cart = request.session.get('cart', {})
    quantity_dict = request.session.get('quantity_dict', {})
    # total = request.session.total

    for product_name in cart: # y = quantity, should print 1
        print (product_name,':',cart[product_name]) # Print the current cart

    form = OrderForm()
    # order = Ordenes.objects.all()

mysite/shopping_cart/views.py
#from django.shortcuts import render


from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.urls import reverse
from django.shortcuts import render, redirect, get_object_or_404

from accounts.models import Perfil
from Catalogo.models import Producto

from shopping_cart.extras import generate_order_id, transact, generate_client_token
from shopping_cart.models import OrderItem, Order, Transaction

import datetime
# Create your views here.


def get_user_pending_order(request):
    # get order for the correct user
    user_profile = get_object_or_404(Perfil, user=request.user)
    order = Order.objects.filter(owner=user_profile, is_ordered=False)
    if order.exists():
        # get the only order in the list of filtered orders
        return order[0]
    return 0


@login_required()
def add_to_cart(request, **kwargs):
    # get the user profile
    user_profile = get_object_or_404(Perfil, user=request.user)
    # filter products by id
    product = Producto.objects.filter(id=kwargs.get('item_id', "")).first()
    # check if the user already owns this product
    # if product in request.user.profile.ebooks.all():
    #     messages.info(request, 'Ya tienes este producto')
    #     return redirect(reverse('products:catalogo')) 
    # create orderItem of the selected product
    order_item, status = OrderItem.objects.get_or_create(product=product)
    # create order associated with the user
    user_order, status = Order.objects.get_or_create(owner=user_profile, is_ordered=False)
    user_order.items.add(order_item)
    if status:
        # generate a reference code
        user_order.ref_code = generate_order_id()
        user_order.save()

    # show confirmation message and redirect back to the same page
    messages.info(request, "Articulo agregado al carrito de compras")
    return redirect(reverse('products:catalogo'))


@login_required()
def delete_from_cart(request, item_id):
    item_to_delete = OrderItem.objects.filter(pk=item_id)
    if item_to_delete.exists():
        item_to_delete[0].delete()
        messages.info(request, "Articulo eliminado del carrito")
    return redirect(reverse('shopping_cart:order_summary'))


@login_required()
def order_details(request, **kwargs):
    existing_order = get_user_pending_order(request)
    context = {
        'order': existing_order
    }
    return render(request, 'shopping_cart/resumencompra.html', context)



@login_required()
def update_transaction_records(request, token):
    # get the order being processed
    order_to_purchase = get_user_pending_order(request)

    # update the placed order
    order_to_purchase.is_ordered=True
    order_to_purchase.date_ordered=datetime.datetime.now()
    order_to_purchase.save()
    
    # get all items in the order - generates a queryset
    order_items = order_to_purchase.items.all()

    # update order items
    order_items.update(is_ordered=True, date_ordered=datetime.datetime.now())

    # Add products to user profile
    user_profile = get_object_or_404(Perfil, user=request.user)
    # get the products from the items
    order_products = [item.product for item in order_items]
    user_profile.ebooks.add(*order_products)
    user_profile.save()

    
    # create a transaction
    transaction = Transaction(profile=request.user.profile,
                            token=token,
                            order_id=order_to_purchase.id,
                            amount=order_to_purchase.get_cart_total(),
                            success=True)
    # save the transcation (otherwise doesn't exist)
    transaction.save()


    # send an email to the customer
    # look at tutorial on how to send emails with sendgrid
    messages.info(request, "Compra Exitosa, alguien se pondra en contacto con usted para darle seguimiento a su compra")
    return redirect(reverse('accounts:my_profile'))


def success(request, **kwargs):
    # a view signifying the transcation was successful
    return render(request, 'shopping_cart/compraexitosa.html', {})

mysite/templates/Catalogo/cat_results.html
<div class="row panel">
  {% for p in result %}
    <div class="col-md-4">
      {% for i in p.imagenes.all|slice:":1" %}
      <a href="{% url 'Catalogo:producto' p.id %}"><img src="../media/{{ i.path }}" class="img-thumbnail img-fluid text-center" alt="Imagen no encontrada." /></a>
      {% endfor %}
      <h3 class="title" align="" style="padding-left: 60px;">Nombre: {{ p.nombre }}</h3>
      <h3 class="title" align="" style="padding-left: 60px;">Precio: {{ p.precio }}$</h3>
    </div>
  {% endfor %}
</div>

mysite/templates/Catalogo/catalogo.html
<div class="basic">
{% load static %}
{% include "partials/top.html" %}
</div>
<div class="container panel">

    <div class="row panel">
        <div class="col-sm-4">
            <h1 class="title">
                Catálogo
            </h1>
        </div>
    </div>
    <hr>


    <h2>Filtros</h2>

    <form autocomplete="off" action="/AJAXSearchCat">
      {% csrf_token %}
      <div class="row">
        <div class="form-group col-sm-3 col-md-3">
            <label for="nombre">Nombre del Producto:</label>
            <input class="form-control" type="text" name="nombre" id="nombre">
        </div>


        <div class="form-group col-sm-4 col-md-3">
          <label for="comunidad">Select list:</label>
          <select class="form-control" id="comunidad" name="comunidad">
              <option value="">Todas las comunidades</option>
            {% for com in communities %}
              <option value="{{ com.nombre }}">{{ com.nombre }}</option>
            {% endfor %}
          </select>
        </div>


        <div class="form-group col-sm-3 col-md-3">
            <label for="precio__gt">Precio mayor o igual a:</label>
            <input class="form-control" type="number" min="0" name="precio__gt" id="precio__gt">
        </div>


        <div class="form-group col-sm-3 col-md-3">
            <label for="precio__lt">Precio menor o igual a:</label>
            <input class="form-control" type="number" min="0" name="precio__lt" id="precio__lt">
        </div>
        <!--<input type="submit" name="" value="Submit">-->
      </div>
      <!--<input type="submit" name="" value="Enviar">-->
    </form>

    <p id="prueba"></p>

    <script type="text/javascript">

    $(document).ready(function(){

    /**
      When the doc is ready
      load original form fields (serialize)
      to compare and detect changes
    */

    var $form = $('form'),
    origForm = $form.serialize();


    /**
    Preload all results of communities,
    to be filtered when form changes
    */
    $.ajax({
          type: "POST",
          url: "/AJAXSearchCat/",
          data: {
            'comunidad': $('#comunidad').val(),
            'nombre': $('#nombre').val(),
            'precio__gt': $('#precio__gt').val(),
            'precio__lt': $('#precio__lt').val(),
            'csrfmiddlewaretoken':"{{ csrf_token }}"
          },
          success : function(data) {
              $('#getResultsCat').html(data);
          }
      })


      /*
        Detect changes on form
        and fire ajax search when that happens
        Warning: starts detecting (even when all is erased)
        only after the first change.
        Preload of options is needed
      */
    $('form :input').on('change input', function() {
      //$('.change-message').toggle($form.serialize() !== origForm);
      //ajax function
      //$('#getResults').html("aaaa");
        var search_nombre, search_desc;
        search_nombre=$('#nombre').val();
        search_desc=$('#desc').val();
        //$("#prueba").text("nombre: "+$('#nombre').val()+" comunidad: "+$('#comunidad').val()+" precio__gt: "+$('#precio__gt').val() +" precio__lt: "+$('#precio__lt').val());
        //$('#getResults').html("aaaa");  // debugging

        $.ajax({
              type: "POST",
              url: "/AJAXSearchCat/",
              data: {
                'comunidad': $('#comunidad').val(),
                'nombre': $('#nombre').val(),
                'precio__gt': $('#precio__gt').val(),
                'precio__lt': $('#precio__lt').val(),
                'csrfmiddlewaretoken':"{{ csrf_token }}"
              },
              success : function(data) {
                  $('#getResultsCat').html(data);
              }
          })

      });

    });

    </script>


    <div id="getResultsCat"></div>


<!--
    <div class="row panel">
      {# for p in products %}
        <div class="col-md-4">
          {# for i in p.imagenes.all|slice:":1" %}
          <a href="{# url 'Catalogo:producto' p.id %}"><img src="../media/{{ i.path }}" class="img-thumbnail img-fluid text-center" alt="Imagen no encontrada." /></a>
          {# endfor %}
          <h3 class="title" align="" style="padding-left: 60px;">Nombre: {{ p.nombre }}</h3>
          <h3 class="title" align="" style="padding-left: 60px;">Precio: {{ p.precio }}$</h3>
        </div>
      {# endfor %}
    </div>
-->


<!--
    <div class="row">
      <div class="pagination">
        <span class="step-links">
          <h5 class="title" align="center">
          {# if products.has_previous %}
                <a href="?page=1">&laquo; primera</a>
                <a href="?page={#{ products.previous_page_number }}">anterior</a>
            {# endif %}

            <span class="current">
                Page {#{ products.number }} of {#{ products.paginator.num_pages }}.
            </span>

            {# if products.has_next %}
                <a href="?page={#{ products.next_page_number }}">siguiente</a>
                <a href="?page={#{ products.paginator.num_pages }}">ultima &raquo;</a>
            {# endif %}
          </h5>
        </span>
      </div>
    </div>
-->


</div class="container">

<div class="basic">
{% include "partials/bottom.html" %}
</div>

mysite/templates/Catalogo/catalogoFilter.html
<div class="basic">
{% load static %}
{% load bootstrap %}
{% load widget_tweaks %}
{% include "partials/top.html" %}
</div>
<div class="container panel">

    <div class="row">
        <div class="col-sm-4">
            <h1 class="title">
                Catálogo
            </h1>
        </div>
        <div class="col-sm-4">
        </div>

    </div>



    <br>
    <form method="get">
      {% csrf_token %}
      <!--Cambiar fondo de forma? add class="well" -->
        <div class="">
            <h3 style="margin-top: 0">Filtrar</h3>
            <div class="row">
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.nombre.label_tag }}
                    {% render_field filter.form.nombre class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.communidad.label_tag }}
                    {% render_field filter.form.communidad class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.precio__gt.label_tag }}
                    {% render_field filter.form.precio__gt class="form-control" %}
                </div>
                <div class="form-group col-sm-4 col-md-3">
                    {{ filter.form.precio__lt.label_tag }}
                    {% render_field filter.form.precio__lt class="form-control" %}
                </div>
            </div>
            <button type="submit" class="btn btn-primary">
                <span class="glyphicon glyphicon-search"></span> Buscar
            </button>
        </div>
    </form>

    <hr>
    <div class="row">
      {% for p in filter.qs %}
        <div class="col-md-5">
          {% for i in p.imagenes.all|slice:":1" %}
          <a href="{% url 'Catalogo:producto' p.id %}"><img src="../media/{{ i.path }}" class="img-thumbnail img-fluid text-center" alt="Imagen no encontrada." /></a>
          {% endfor %}
          <h3 class="title" align="" style="padding-left: 60px;">Nombre: {{ p.nombre }}</h3>
          <h3 class="title" align="" style="padding-left: 60px;">Precio: {{ p.precio }}$</h3>
        </div>
      {% endfor %}
    </div>

    <div class="row">
      <div class="pagination">
        <span class="step-links">
          <h5 class="title" align="center">
          {% if products.has_previous %}
                <a href="?page=1">&laquo; primera</a>
                <a href="?page={{ products.previous_page_number }}">anterior</a>
            {% endif %}

            <span class="current">
                Page {{ products.number }} of {{ products.paginator.num_pages }}.
            </span>

            {% if products.has_next %}
                <a href="?page={{ products.next_page_number }}">siguiente</a>
                <a href="?page={{ products.paginator.num_pages }}">ultima &raquo;</a>
            {% endif %}
          </h5>
        </span>
      </div>
    </div>
</div class="container">
<div class="basic">
{% include "partials/bottom.html" %}
</div>

mysite/templates/Catalogo/shoppingcart.html
<div class="basic">
{% load static %}
{% include "partials/top.html" %}
</div>
<div class="container">


{% if messages %}
      {% for message in messages %}
      <div {% if message.tags %}  class="alert alert-danger {{ message.tags }}"{% endif %}>
        <strong>¡Hola!</strong> {{ message }}
      </div>
      {% endfor %}
  {% endif %}

    <div class="row">
        <div class="col-sm-4">
            <h1 class="title">
                Tu Carrito de Compras
            </h1>
        </div>
        <div class="col-sm-4">
        </div>
<!--         <div class="col-sm-4">
            <input type="text" placeholder="Search..">
        </div> -->
    </div>
    <hr>
<!-- <table> -->

<!-- <tr>    -->
<!-- <td><h5>{{ producto.nombre }}</h5> -->
<!-- <td><p><strong>$ {{ producto.precio }}</strong></p></td> -->
<style>
table {
    font-family: arial, sans-serif;
    border-collapse: collapse;
    width: 100%;
}

td, th {
    /*border: 1px solid #dddddd;*/
    text-align: center;
    padding: 10px;
}

#checkout{
  position: relative;
  bottom: 30%;

}
.position{
  margin-top: 40px;
}

</style>

<table align="center" class = "panel">
  <tr>
    {% if request.session.total > 0 %}
    <td> </td>
    <td> </td>
    <td><h2>Producto</h2></td>
    <td></td>
    <td></td>
    <td ><h2>Cantidad</h2></td>
    <td><h2>Costo Total por Producto</h2></td>

      

    {% else %}
      <td><h3><i>Tu carrito de Compras esta actualmente vacio. Agrega un producto para poder proceder.</i></h3></td>
    {% endif %}

  </tr>

<!--
Para ciclar e insertar la cantidad correcta, pon otro for pero que imprima cuando el nombre del producto de la cantidad coincida con el nombre del producto en el carrito
-->

{% for key,value in cart.items %}



  <form method='POST'>
  <tr align="center">
    <td>
      <button type="submit" name="boton{{ key }}" value="Quitar Producto del Carrito de Compras" class="close" id="boton{{ key }}" aria-label="Close">
        <span aria-hidden="true">&times;</span>
      </button>
    </td>
    


     {% for p in products %}
     {% for i in p.imagenes.all|slice:":1" %}
      {% if key == p.nombre %}
        
          <td><a href="{% url 'Catalogo:producto' p.id %}"><img width="150px" src="../media/{{ i.path }}" class="img-thumbnail img-fluid text-center" alt="Imagen no encontrada." /></a></td>
        
      {% endif %}
    {% endfor %}
    {% endfor %}
  <td><h3><i>{{ key }}</i></h3></td><td><td></td></td>
  
  {% for producto,quantity in quantity_dict.items %}
  {% if key == producto  %}
  <td><h3><i>{{ quantity }}</i></h3></td>
  {% endif %}
  {% endfor %}
  <td><h3>$<i>{{ value }}</i></h3></td>
  {% csrf_token %}
  
  </form>
  </tr>
  {% endfor %}

</table>

<hr>

<div class="row panel" align="center">
  <div class="col-md-2"></div>
  <div class="col-md-2"></div>
  
  <div class="col-md-2">
    <h1><i>Total:</i> <b>${{ request.session.total }} </b></h1>
  </div>
  <div class="col-md-2 position"> 
    <a href="{% url 'Catalogo:checkout' %}"><input type="submit" name="checkout" value="Continuar con la Compra" class="btn btn-success active btn-green green-bg" id="checkout"></a>
  </div>



<!-- </td> -->
<!-- </tr> -->
<!-- </table> -->
  </div>


{% include "partials/bottom.html" %}