mysite/Colabora/urls.py
"""
Created by Framework
This file is where the urls of Colabora are declared.
Modified by: Jorge Nino
Date: 19/10/18
"""
# Import the libraries used
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views



# Declare the app name
app_name = 'Colabora'
# Declare the url patterns
urlpatterns = [
    # ex: /polls/
    # Set the path to the view and the name of the window
    path('colabora/', views.colabora, name='colabora'),
]

# If the debug setting is on
if settings.DEBUG:
    # Add the patterns of the images
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/Contacto/urls.py
"""
Created by Framework
This file is where you can set the urls to your views.
Modified by: Jorge Nino
Date: 19/10/18
"""
# Import libraries needed
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Declare the app name
app_name = 'Contacto'
# Declare the url patterns
urlpatterns = [
    # ex: /polls/
    path('contacto/', views.contactanos, name='contacto'),
]

# If the debug setting is on
if settings.DEBUG:
    # Add the patterns of the images
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/Inicio/urls.py
"""
Created by Framework
This file is where you can set the urls to your views.
Modified by: Jorge Nino
Date: 19/10/18
"""
# Import libraries needed
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views



app_name = 'Inicio'
urlpatterns = [
    path('',views.index,name='index'),
    path('api/',views.ChartView.as_view(),name='charts'),
    path('api/data/',views.get_data,name='get_data'),
    path('api/chart/data/',views.ChartData.as_view(),name='chart_data'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/Somos/urls.py
"""
Created by Framework
This file is where you can set the urls to your views.
Modified by: Jorge Nino
Date: 19/10/18
"""
# Import libraries needed
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Set the name of the app
app_name = 'Somos'

# Declare the url patterns of the app views
urlpatterns = [
    # ex: /polls/
    path('quiensomos/', views.quiensomos, name='quiensomos'),
]

mysite/catalogo/urls.py
"""
Created by Framework
This file is where you can set the urls to your views.
Modified by: Jorge Nino
Date: 19/10/18
"""

# Import libraries used
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views


# Set the name of the app
app_name = 'Catalogo'
# Declare the url patterns for each view.
urlpatterns = [
    # ex: /polls/

    path('search-submit/', views.SearchSubmitView.as_view(), name='search-submit'),
    path('search-ajax-submit/', views.SearchAjaxSubmitView.as_view(), name='search-ajax-submit'),

    path('catalogo/',views.catalogo,name='catalogo'),
    path('AJAXSearchCat/', views.AJAXSearchCat, name='ajaxSearchCat'),

    path('catalogo2/', views.catalogoFilter.as_view(),name='catalogo2'),
    path('catalogo/<int:productoid>/', views.getProducto, name='producto'),
    path('carrito/', views.viewCart, name='carrito'),
    path('checkout/', views.checkout, name = 'checkout'),
]
# if debug is on show images through their url.
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('',include('Inicio.urls')),
    path('',include('Comunidades.urls')),
    path('',include('Catalogo.urls')),
    path('',include('Somos.urls')),
    path('',include('Contacto.urls')),
    path('',include('Actividades.urls')),
    path('',include('Colabora.urls')),
    path('admin/', admin.site.urls),

    path('', include('accounts.urls')),
    path('', include('shopping_cart.urls')),

]

mysite/templates/partials/bottom.html
</body>
<br>
{% load static %}
{% if contacto %}
<footer class="footer" style="position: fixed; bottom: 0px; width: 100%; height: 170px;">
  <div class="row">
  <div class="col-md-2">
      <img src="{% static "index/images/logo.png" %}" style="width: 62%;height: 100%;" class="img-thumbnail img-fluid text-center" alt="Imagen no encontrada"/>
  </div>
  <div class="col-md-10">
  {% for con in contacto %}
    <div class="row">
      <div class="col-md-4">
        <h3>{{ con.telefono }}</h3>
      </div>
      <div class="col-md-4">
        <h3>{{ con.mail }}</h3>
      </div>
      <div class="col-md-4">
        <h3>{{ con.horario }}</h3>
      </div>
    </div>
  {% endfor %}
</div>
</div>
</footer>
{% else %}
<footer class="footer" style="position: fixed; bottom: 0px; width: 100%; height: 60px;">
    <div class="row">
			<div class="col-md-4">
				Contacto
			</div>
			<div class="col-md-4">
				Numero
			</div>
			<div class="col-md-4">
				Etc
			</div>
		</div>
    <div class="row">
			<div class="col-md-4">
				Contacto
			</div>
			<div class="col-md-4">
				Numero
			</div>
			<div class="col-md-4">
				Etc
			</div>
		</div>
    <div class="row">
			<div class="col-md-4">
				Contacto
			</div>
			<div class="col-md-4">
				Numero
			</div>
			<div class="col-md-4">
				Etc
			</div>
		</div>
</footer>
{% endif %}
</html>

mysite/templates/partials/top.html
<!DOCTYPE html>
<html lang="en">
<head>
    {% load static %}
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
    <script src="{% static '/js/script.js' %}"></script>

    <!-- Add intercooler library   -->
    <script src="https://code.jquery.com/jquery-3.1.1.min.js"></script>
    <script src="https://intercoolerreleases-leaddynocom.netdna-ssl.com/intercooler-1.1.1.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static '/css/styles.css' %}">
  <meta charset="UTF-8">
    <title>Todos Somos Comunidad</title>
</head>
<body>
  <nav class="navbar navbar-default">
      <!-- Brand and toggle get grouped for better mobile display -->
      <div class="navbar-header">
          <button type="button" data-target="#navbarCollapse" data-toggle="collapse" class="navbar-toggle">
              <span class="sr-only">Toggle navigation</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
          </button>
          <a id="logo" class="navbar-brand" href="{% url 'Inicio:index' %}"><img src="{% static "index/images/logo.png" %}" alt="Logo no encontrado"></a>
          <!--<a href="#" class="navbar-brand"><img src="{% static "/index/images/logo.png" %}" height="40" width="35"/></a>-->
      </div>
      <!-- Collection of nav links and other content for toggling -->
      <div id="navbarCollapse" class="collapse navbar-collapse">
          <ul class="nav navbar-nav">
              <li class="active"><a href="{% url 'Inicio:index' %}">Inicio</a></li>
              <li><a href="{% url 'Somos:quiensomos' %}">Quienes Somos</a></li>
              <li><a href="{% url 'Actividades:actividades' %}">Actividades</a></li>
              <li><a href="{% url 'Comunidades:comunidades' %}">Comunidades</a></li>
              <li><a href="{% url 'Colabora:colabora' %}">Colabora</a></li>
              <li><a href="{% url 'Catalogo:catalogo' %}">Catálogo</a></li>
              <li><a href="{% url 'Contacto:contacto' %}">Contacto</a></li>
          </ul>
          <ul class="nav navbar-nav navbar-right">
              <li><a href="{% url 'Catalogo:carrito' %}"><img src="{% static "/index/images/Grocery_Cart.png" %}" height="20px"></a></li>
             <!--  <li><a href="#!">PayPal</a></li> -->
             <!-- PAYPAL DONATION -->
             <li style="padding-top: 10px;"><!-- <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                  <input type="hidden" name="cmd" value="_s-xclick">
                  <input type="hidden" name="hosted_button_id" value="LGTHJAR7947WY">
                  <input type="image" src="https://www.paypalobjects.com/es_XC/i/btn/btn_donate_LG.gif" border="0" name="submit" alt="PayPal, la forma más segura y rápida de pagar en línea.">
                  <img alt="" border="0" src="https://www.paypalobjects.com/es_XC/i/scr/pixel.gif" width="1" height="1"> </form> -->
                  <form action="https://www.paypal.com/cgi-bin/webscr" method="post" target="_top">
                      <input type="hidden" name="cmd" value="_s-xclick">
                      <input type="hidden" name="hosted_button_id" value="LGTHJAR7947WY">
                      <input type="image" src="https://www.paypalobjects.com/es_XC/i/btn/btn_donate_SM.gif" border="0" name="submit" alt="PayPal, la forma más segura y rápida de pagar en línea.">
                      <!-- <img alt="" border="0" src="https://www.paypalobjects.com/es_XC/i/scr/pixel.gif" width="1" height="1"> -->
                </form>
             </li>

          </ul>
      </div>
  </nav>
  <!-- Al parecer si se inserta el script aqui el codigo funciona -->

  <!-- Ademas, el codigo que se uso es distinto al que se tiene en script.js -->
  <script type="text/javascript">
      $(document).ready(function() {
        $('li.active').removeClass('active');
        $('a[href="' + location.pathname + '"]').closest('li').addClass('active');
      });
  </script>
  <br>